# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
dist: trusty
warnings_are_errors: false

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal1-dev
      - libproj-dev

# Code coverage
r_packages:
  - covr

after_success:
- Rscript -e 'library(covr); codecov()'

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true