---
title: "Gap Analysis workflow for Multiple Species"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Gap Analysis for Multiple Species}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include = FALSE}
load("C:/Users/sgora/Desktop/Agrobiodiversity/GapR/GapAnalysis/data/CucurbitaData.rda")

```

## Introduction
This vignette outlines a reproducible workflow for conducting gap analysis for multiple species using spatial data, species distribution models (SDMs), and environmental layers. Three different methods for processing and storing results are explored: (1) using named lists, (2) conditional binding, and (3) functional programming with the `{purrr}` package. These examples provide flexibility for users based on their data and needs.

## Workflow for multiple species 
Before conducting a gap analysis, we first load the necessary packages and datasets. The `{dplyr}` package is used for data manipulation, `{terra}` handles spatial data, and `{sf}` manages shapefiles. The datasets used in this analysis include occurrence data for Cucurbita (gourd plant) species, SDMs, a raster layer of protected areas, and ecoregion boundaries.

Load packages.
```r
pacman::p_load(dplyr, terra, sf)
```

Load data.

```r
load("data/CucurbitaData.rda")      # Occurrence data
load("data/CucurbitaRasts.rda")     # Raster list
load("data/protectAreasRast.rda")   # Protected areas raster
load("data/ecoExample.rda")         # Ecoregions data
```

To streamline analysis, we create a list of unique species names from the occurrence data where subsequent steps are applied consistently to each species.
```r
taxa <- unique(CucurbitaData$species)
```



### Example 1: Using a named list and for-loop

```r
# Create an empty named list to store results
results_list <- list()

# Run using a for loop
for (i in seq_along(taxa)) {
  taxon <- taxa[i]

  # Assign the data for the selected taxon
  sdm <- terra::unwrap(CucurbitaRasts)[[i]]
  occurrence_Data <- CucurbitaData[CucurbitaData$species == taxon, ]
  ecoregions <- terra::vect(eco1)
  protectAreasRast <- terra::unwrap(protectAreasRast)

  # Generate gBuffer
  gBuffer <- generateGBuffers(taxon = taxon, occurrence_Data = occurrence_Data, bufferDistM = 50000)

  # Ex-situ analysis
  srsex <- SRSex(taxon = taxon, occurrence_Data = occurrence_Data)
  grsex <- GRSex(taxon = taxon, sdm = sdm, gBuffer = gBuffer)
  ersex <- ERSex(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, gBuffer = gBuffer, ecoregions = ecoregions, idColumn = "ECO_ID_U")
  fcsex <- FCSex(taxon = taxon, srsex = srsex, grsex = grsex, ersex = ersex)

  # In-situ analysis
  srsin <- SRSin(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, protected_Areas = protectAreasRast)
  grsin <- GRSin(taxon = taxon, sdm = sdm, protected_Areas = protectAreasRast)
  ersin <- ERSin(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, protected_Areas = protectAreasRast, ecoregions = ecoregions, idColumn = "ECO_ID_U")
  fcsin <- FCSin(taxon = taxon, srsin = srsin, grsin = grsin, ersin = ersin)

  # FCSmean calculation
  fcsmean <- FCSc_mean(taxon = taxon, fcsin = fcsin, fcsex = fcsex)

  # Store results in the named list
  results_list[[taxon]] <- list(
    srsex = srsex, grsex = grsex, ersex = ersex, fcsex = fcsex,
    srsin = srsin, grsin = grsin, ersin = ersin, fcsin = fcsin, fcsmean = fcsmean
  )

  # Print results
  print(paste("Taxon:", taxon))
  print(srsex)
  print(grsex)
  print(ersex)
  print(fcsex)
  print(srsin)
  print(grsin)
  print(ersin)
  print(fcsin)
  print(fcsmean)
}
```

**Expected output** sample structure for a single taxon (e.g., *Cucurbita cordata*):

```r
> "Taxon: Cucurbita_cordata"
> Taxon Total.records Total.with.cooordinates Total.G.records
> Cucurbita_cordata           210                     139               3
> G.records.with.coordinates Total.H.records H.records.with.coordinates SRS.exsitu
>                          1             207                        138   1.449275       >  Taxon Area.of.model.km2 G.buffer.areas.in.model.km2 GRS.exsitu
> Cucurbita_cordata          61585.17                    7503.299   12.18361
>               Taxon Ecoregions.with.records Ecoregions.within.G.buffer ERS.exsitu
> Cucurbita_cordata                       7                          2   28.57143
>       Ecoregion id outside G buffer
> 17086, 17095, 10415, 10476, 10428
>               Taxon SRS.exsitu GRS.exsitu ERS.exsitu FCS.exsitu FCS.existu.score
> Cucurbita_cordata   1.449275   28.57143   12.18361   14.06811               NA
> FCS existu score
>               UP
>               Taxon Total.records Records.in.Protected.areas SRS.insitu
> Cucurbita_cordata           115                         91   79.13043
>               Taxon Area.of.model.km2 Area.in.protected.ares.km2 GRS.insitu
> Cucurbita_cordata             61585                      38384   62.32629
>               Taxon Ecoregions.within.model Ecoregions.with.protected.areas ERS.insitu
> Cucurbita_cordata                       7                               6   85.71429
>               Taxon SRS.insitu GRS.insitu ERS.insitu FCS.insitu FCS.insitu.score FCS_Score
> Cucurbita_cordata   79.13043   85.71429   62.32629   75.72367               NA        LP
>               Taxon FCS.exsitu FCS.insitu FCSc_min FCSc_max FCSc_mean FCSc_min_class
> Cucurbita_cordata   14.06811   75.72367 14.06811 75.72367  44.89589             UP
>   FCSc_max_class FCSc_mean_class
>              LP              HP
```


### Example 2: Using conditonal binding and a for-loop
This method conditionally binds new results to the data frame. It provides flexibility when dealing with outputs of varying structure or size.

```r
# Create an empty dataframe to store results
results_df <- NULL

# Run using a for loop
for (i in seq_along(taxa)) {
  taxon <- taxa[i]

  # Assign the data for the selected taxon
  sdm <- terra::unwrap(CucurbitaRasts)[[i]]
  occurrence_Data <- CucurbitaData[CucurbitaData$species == taxon, ]
  ecoregions <- terra::vect(eco1)
  protectAreasRast <- terra::unwrap(protectAreasRast)

  # Generate gBuffer
  gBuffer <- generateGBuffers(taxon = taxon, occurrence_Data = occurrence_Data, bufferDistM = 50000)

  # Ex-situ analysis
  srsex <- SRSex(taxon = taxon, occurrence_Data = occurrence_Data)
  grsex <- GRSex(taxon = taxon, sdm = sdm, gBuffer = gBuffer)
  ersex <- ERSex(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, gBuffer = gBuffer, ecoregions = ecoregions, idColumn = "ECO_ID_U")
  fcsex <- FCSex(taxon = taxon, srsex = srsex, grsex = grsex, ersex = ersex)

  # In-situ analysis
  srsin <- SRSin(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, protected_Areas = protectAreasRast)
  grsin <- GRSin(taxon = taxon, sdm = sdm, protected_Areas = protectAreasRast)
  ersin <- ERSin(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, protected_Areas = protectAreasRast, ecoregions = ecoregions, idColumn = "ECO_ID_U")
  fcsin <- FCSin(taxon = taxon, srsin = srsin, grsin = grsin, ersin = ersin)

  # FCSmean calculation
  fcsmean <- FCSc_mean(taxon = taxon, fcsin = fcsin, fcsex = fcsex)

  # Store results using conditional binding
  if (is.null(results_df)) {
    results_df <- data.frame(
      taxon = taxon,
      srsex = srsex, grsex = grsex, ersex = ersex, fcsex = fcsex,
      srsin = srsin, grsin = grsin, ersin = ersin, fcsin = fcsin, fcsmean = fcsmean
    )
  } else {
    results_df <- bind_rows(
      results_df,
      data.frame(
        taxon = taxon,
        srsex = srsex, grsex = grsex, ersex = ersex, fcsex = fcsex,
        srsin = srsin, grsin = grsin, ersin = ersin, fcsin = fcsin, fcsmean = fcsmean
      )
    )
  }

  # Print results
  print(paste("Taxon:", taxon))
  print(srsex)
  print(grsex)
  print(ersex)
  print(fcsex)
  print(srsin)
  print(grsin)
  print(ersin)
  print(fcsin)
  print(fcsmean)
}
```

**Expected output** sample structure for a single taxon (e.g., *Cucurbita cordata*):

```r
> "Taxon: Cucurbita_cordata"
> Taxon Total.records Total.with.cooordinates Total.G.records
> Cucurbita_cordata           210                     139               3
> G.records.with.coordinates Total.H.records H.records.with.coordinates SRS.exsitu
>                          1             207                        138   1.449275       >  Taxon Area.of.model.km2 G.buffer.areas.in.model.km2 GRS.exsitu
> Cucurbita_cordata          61585.17                    7503.299   12.18361
>               Taxon Ecoregions.with.records Ecoregions.within.G.buffer ERS.exsitu
> Cucurbita_cordata                       7                          2   28.57143
>       Ecoregion id outside G buffer
> 17086, 17095, 10415, 10476, 10428
>               Taxon SRS.exsitu GRS.exsitu ERS.exsitu FCS.exsitu FCS.existu.score
> Cucurbita_cordata   1.449275   28.57143   12.18361   14.06811               NA
> FCS existu score
>               UP
>               Taxon Total.records Records.in.Protected.areas SRS.insitu
> Cucurbita_cordata           115                         91   79.13043
>               Taxon Area.of.model.km2 Area.in.protected.ares.km2 GRS.insitu
> Cucurbita_cordata             61585                      38384   62.32629
>               Taxon Ecoregions.within.model Ecoregions.with.protected.areas ERS.insitu
> Cucurbita_cordata                       7                               6   85.71429
>               Taxon SRS.insitu GRS.insitu ERS.insitu FCS.insitu FCS.insitu.score FCS_Score
> Cucurbita_cordata   79.13043   85.71429   62.32629   75.72367               NA        LP
>               Taxon FCS.exsitu FCS.insitu FCSc_min FCSc_max FCSc_mean FCSc_min_class
> Cucurbita_cordata   14.06811   75.72367 14.06811 75.72367  44.89589             UP
>   FCSc_max_class FCSc_mean_class
>              LP              HP
```


### Example 3: `purrr` function

To streamline the gap analysis for multiple species, we use the `{purrr}` package. The `purrr::map2()` function applies a predefined workflow (`purrrWorkflow`) to each combination of species and its corresponding SDM. This approach minimizes repetitive code and automates looping, making it efficient for larger datasets

```r
#Load purrr package
library(purrr)

# Prep list of species
speciesList <- unique(CucurbitaData$species)

# Prep raster datasets to make sure the correct one is selected
sdms <- terra::unwrap(CucurbitaRasts)
# Match the order of the SDMs to the order of the species in the taxa object
sdmList <- list(
  sdms$cordata,
  sdms$digitata,
  sdms$palmata
)
names(sdmList) <- taxa

# Define the workflow function
purrrWorkflow <- function(taxon, sdms) {
  sdm <- sdms[taxon][[1]] # Extract the raster from the list object
  
  # Assign the data for the selected taxon
  occurrence_Data <- CucurbitaData[CucurbitaData$species == taxon, ]
  ecoregions <- terra::vect(eco1)
  protectAreasRast <- terra::unwrap(protectAreasRast)
  
  # Generate gBuffer
  gBuffer <- generateGBuffers(taxon = taxon, occurrence_Data = occurrence_Data, bufferDistM = 50000)
  
  # Ex-situ analysis
  srsex <- SRSex(taxon = taxon, occurrence_Data = occurrence_Data)
  grsex <- GRSex(taxon = taxon, sdm = sdm, gBuffer = gBuffer)
  ersex <- ERSex(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, gBuffer = gBuffer, ecoregions = ecoregions, idColumn = "ECO_ID_U")
  fcsex <- FCSex(taxon = taxon, srsex = srsex, grsex = grsex, ersex = ersex)
  
  # In-situ analysis
  srsin <- SRSin(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, protected_Areas = protectAreasRast)
  grsin <- GRSin(taxon = taxon, sdm = sdm, protected_Areas = protectAreasRast)
  ersin <- ERSin(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, protected_Areas = protectAreasRast, ecoregions = ecoregions, idColumn = "ECO_ID_U")
  fcsin <- FCSin(taxon = taxon, srsin = srsin, grsin = grsin, ersin = ersin)
  
  # FCSmean calculation
  fcsmean <- FCSc_mean(taxon = taxon, fcsin = fcsin, fcsex = fcsex)
  
  # Return results as a list
  return(list(
    taxon = taxon,
    srsex = srsex, grsex = grsex, ersex = ersex, fcsex = fcsex,
    srsin = srsin, grsin = grsin, ersin = ersin, fcsin = fcsin, fcsmean = fcsmean
  ))
}

# Run the workflow using purrr::map
results <- purrr::map(.x = speciesList, .f = purrrWorkflow, sdms = sdmList)
names(results) <- speciesList

# Alternative: purrr::map2 (if using two separate lists like speciesList and sdms)
results <- purrr::map2(.x = speciesList, .y = sdmList, .f = function(taxon, sdm) {
  # Include the same logic as above
  occurrence_Data <- CucurbitaData[CucurbitaData$species == taxon, ]
  ecoregions <- terra::vect(eco1)
  protectAreasRast <- terra::unwrap(protectAreasRast)
  
  # Ex-situ and in-situ analyses as above
  gBuffer <- generateGBuffers(taxon = taxon, occurrence_Data = occurrence_Data, bufferDistM = 50000)
  srsex <- SRSex(taxon = taxon, occurrence_Data = occurrence_Data)
  grsex <- GRSex(taxon = taxon, sdm = sdm, gBuffer = gBuffer)
  ersex <- ERSex(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, gBuffer = gBuffer, ecoregions = ecoregions, idColumn = "ECO_ID_U")
  fcsex <- FCSex(taxon = taxon, srsex = srsex, grsex = grsex, ersex = ersex)
  
  srsin <- SRSin(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, protected_Areas = protectAreasRast)
  grsin <- GRSin(taxon = taxon, sdm = sdm, protected_Areas = protectAreasRast)
  ersin <- ERSin(taxon = taxon, sdm = sdm, occurrence_Data = occurrence_Data, protected_Areas = protectAreasRast, ecoregions = ecoregions, idColumn = "ECO_ID_U")
  fcsin <- FCSin(taxon = taxon, srsin = srsin, grsin = grsin, ersin = ersin)
  
  fcsmean <- FCSc_mean(taxon = taxon, fcsin = fcsin, fcsex = fcsex)
  
  return(list(
    taxon = taxon,
    srsex = srsex, grsex = grsex, ersex = ersex, fcsex = fcsex,
    srsin = srsin, grsin = grsin, ersin = ersin, fcsin = fcsin, fcsmean = fcsmean
  ))
})

# Display results
results
```


**Expected output** sample structure for a single taxon (e.g., *Cucurbita cordata*):

```r
> [[2]]
> [[1]]$taxon
> [1] "Cucurbita_cordata"
> 
> [[1]]$srsex
>               Taxon Total.records Total.with.cooordinates Total.G.records
> 1 Cucurbita_cordata           210                     139               3
>   G.records.with.coordinates Total.H.records H.records.with.coordinates SRS.exsitu
> 1                          1             207                        138   1.449275
> 
> [[1]]$grsex
>               Taxon Area.of.model.km2 G.buffer.areas.in.model.km2 GRS.exsitu
> 1 Cucurbita_cordata          61585.17                    7503.299   12.18361
> 
> [[1]]$ersex
>               Taxon Ecoregions.with.records Ecoregions.within.G.buffer ERS.exsitu
> 1 Cucurbita_cordata                       7                          2   28.57143
>       Ecoregion id outside G buffer
> 1 17086, 17095, 10415, 10476, 10428
> 
> [[1]]$fcsex
>               Taxon SRS.exsitu GRS.exsitu ERS.exsitu FCS.exsitu FCS.existu.score
> 1 Cucurbita_cordata   1.449275   28.57143   12.18361   14.06811               NA
>   FCS existu score
> 1               UP
> 
> [[1]]$srsin
>               Taxon Total.records Records.in.Protected.areas SRS.insitu
> 1 Cucurbita_cordata           115                         91   79.13043
> 
> [[1]]$grsin
>               Taxon Area.of.model.km2 Area.in.protected.ares.km2 GRS.insitu
> 1 Cucurbita_cordata             61585                      38384   62.32629
> 
> [[1]]$ersin
>               Taxon Ecoregions.within.model Ecoregions.with.protected.areas ERS.insitu
> 1 Cucurbita_cordata                       7                               6   85.71429
> 
> [[1]]$fcsin
>               Taxon SRS.insitu GRS.insitu ERS.insitu FCS.insitu FCS.insitu.score FCS_Score
> 1 Cucurbita_cordata   79.13043   85.71429   62.32629   75.72367               NA        LP
> 
> [[1]]$fcsmean
>               Taxon FCS.exsitu FCS.insitu FCSc_min FCSc_max FCSc_mean FCSc_min_class
> 1 Cucurbita_cordata   14.06811   75.72367 14.06811 75.72367  44.89589             UP
>   FCSc_max_class FCSc_mean_class
> 1             LP              HP
```


## Closing Remarks

In this vignette, we demonstrated three methods for conducting a multi-species gap analysis. By applying these approaches, users can identify conservation gaps and prioritize actions to enhance biodiversity protection. We hope these workflows serve as a foundation for further adaptations in your research projects.
