suppressWarnings(suppressMessages(library(raster)))
lfiles <-list.files("data-raw/exampleData/sdm_rasters",full.names = T)
sdm_rasters <- lapply(1:length(lfiles), function(i){
  x <- raster::raster(lfiles[[i]])
  return(x)
})
# cordata <- raster::raster("data-raw/exampleData/sdm_rasters/cordata.tif")
# digitata <- raster::raster("data-raw/exampleData/sdm_rasters/digitata.tif")
# palmata <- raster::raster("data-raw/exampleData/sdm_rasters/palmata.tif")
# sdm_rasters <- list(cordata,digitata,palmata)
usethis::use_data(sdm_rasters, overwrite = TRUE,compress = "bzip2")
